/*
 * generated by Xtext
 */
package com.avaloq.tools.ddk.checkcfg.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.avaloq.tools.ddk.checkcfg.services.CheckCfgGrammarAccess;

public class CheckCfgParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CheckCfgGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.avaloq.tools.ddk.checkcfg.parser.antlr.internal.InternalCheckCfgParser createParser(XtextTokenStream stream) {
		return new com.avaloq.tools.ddk.checkcfg.parser.antlr.internal.InternalCheckCfgParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "CheckConfiguration";
	}
	
	public CheckCfgGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CheckCfgGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
