/*
 * generated by Xtext
 */
package com.avaloq.tools.ddk.xtext.expression.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ExpressionAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/avaloq/tools/ddk/xtext/expression/parser/antlr/internal/InternalExpression.tokens");
	}
}
