/*
 * generated by Xtext
 */
package com.avaloq.tools.ddk.xtext.valid.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractValidScopeProvider extends DelegatingScopeProvider {
}
