/**
 * generated by Xtext 2.14.0
 */
package com.avaloq.tools.ddk.xtext.format2.format2.impl;

import com.avaloq.tools.ddk.xtext.format2.format2.Format2Package;
import com.avaloq.tools.ddk.xtext.format2.format2.GrammarRuleDirective;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Grammar Rule Directive</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GrammarRuleDirectiveImpl extends MinimalEObjectImpl.Container implements GrammarRuleDirective
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GrammarRuleDirectiveImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Format2Package.Literals.GRAMMAR_RULE_DIRECTIVE;
  }

} //GrammarRuleDirectiveImpl
