/**
 * generated by Xtext 2.14.0
 */
package com.avaloq.tools.ddk.xtext.format2.format2.impl;

import com.avaloq.tools.ddk.xtext.format2.format2.Format2Package;
import com.avaloq.tools.ddk.xtext.format2.format2.NoFormatLocator;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>No Format Locator</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NoFormatLocatorImpl extends LocatorImpl implements NoFormatLocator
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NoFormatLocatorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Format2Package.Literals.NO_FORMAT_LOCATOR;
  }

} //NoFormatLocatorImpl
