/*
 * generated by Xtext 2.26.0
 */
package com.avaloq.tools.ddk.checkcfg.ui.editor;

import org.eclipse.xtext.xbase.ui.editor.XbaseEditor;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class CheckCfgEditor extends XbaseEditor {
}
