/*
 * generated by Xtext 2.14.0
 */
package com.avaloq.tools.ddk.xtext.format.ide


/**
 * Use this class to register ide components.
 */
class FormatIdeModule extends AbstractFormatIdeModule {
}
