/*
 * generated by Xtext 2.27.0.M1
 */
package com.avaloq.tools.ddk.xtext.export.scoping;

import com.avaloq.tools.ddk.xtext.expression.scoping.ExpressionScopeProvider;

public abstract class AbstractExportScopeProvider extends ExpressionScopeProvider {
}
