/*
 * generated by Xtext
 */
package com.avaloq.tools.ddk.xtext.expression.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractExpressionScopeProvider extends XbaseBatchScopeProvider {
}
