/*
 * generated by Xtext 2.26.0
 */
package com.avaloq.tools.ddk.xtext.expression.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractExpressionScopeProvider extends DelegatingScopeProvider {
}
