<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modelinference" nsURI="http://www.avaloq.com/tools/ddk/xtext/modelinference"
    nsPrefix="mi">
  <eClassifiers xsi:type="ecore:EClass" name="InferenceContainer">
    <eOperations name="getFragmentSegment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="object" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getEObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eParameters name="fragmentSegment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
