/*
 * generated by Xtext 2.29.0
 */
package com.avaloq.tools.ddk.checkcfg.ide;


import java.util.List;

import com.avaloq.tools.ddk.xtext.build.AbstractDynamicSetupService;
import com.avaloq.tools.ddk.xtext.build.ILspLanguageSetup;
import com.google.common.collect.ImmutableList;
import com.google.inject.Injector;
import com.google.inject.Module;

/**
 * Generated by com.avaloq.tools.ddk.xtext.generator.builder.LspBuilderIntegrationFragment2.
 */
public class CheckCfgLspBuildSetupService extends AbstractDynamicSetupService implements ILspLanguageSetup {

  @SuppressWarnings("nls")
  private static final String GRAMMAR = "com.avaloq.tools.ddk.checkcfg.CheckCfg";
  @SuppressWarnings("nls")
  private static final List<String> PARENTS = ImmutableList.of(//
     "org.eclipse.xtext.xbase.Xbase" //
     ,"org.eclipse.xtext.xbase.Xtype" //
  );

  public Injector doSetup(Module overrideModule, Module... additionalModules) {
    return new CheckCfgLspBuildSetupGenerated(SETUP_LOCK, overrideModule, additionalModules).createInjectorAndDoEMFRegistration();
  }

  @Override
  public List<String> getParentLanguages() {
    return PARENTS;
  }

  @Override
  public String getLanguageName() {
    return GRAMMAR;
  }

}
