/*
 * generated by Xtext 2.14.0
 */
package com.avaloq.tools.ddk.xtext.format2.parser.antlr;

import com.avaloq.tools.ddk.xtext.format2.parser.antlr.internal.InternalFormat2Parser;
import com.avaloq.tools.ddk.xtext.format2.services.Format2GrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class Format2Parser extends AbstractAntlrParser {

	@Inject
	private Format2GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFormat2Parser createParser(XtextTokenStream stream) {
		return new InternalFormat2Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "FormatConfiguration";
	}

	public Format2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Format2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
