/*******************************************************************************
 * Copyright (c) 2016 Avaloq Group AG and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Avaloq Group AG - initial API and implementation
 *******************************************************************************/

package com.avaloq.tools.ddk.check.formatting;

import com.avaloq.tools.ddk.check.CheckUiInjectorProvider;
import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.formatting2.FormatterPreferenceKeys;
import org.eclipse.xtext.preferences.MapBasedPreferenceValues;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.formatter.FormatterTestHelper;
import org.eclipse.xtext.testing.formatter.FormatterTestRequest;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@InjectWith(CheckUiInjectorProvider.class)
@ExtendWith(InjectionExtension.class)
public class CheckFormattingTest {

  @Inject
  private FormatterTestHelper _formatterTestHelper;

  /**
   * Test that correctly formatted Check sources are not modified.
   */
  @Test
  public void testFormattedSource() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package com.avaloq.tools.ddk.check.formatting");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import com.avaloq.tools.ddk.check.check.*");
    _builder.newLine();
    _builder.newLine();
    _builder.append("catalog CheckFormattingTest");
    _builder.newLine();
    _builder.append("for grammar com.avaloq.tools.ddk.check.Check {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("category \"Label\" {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("/**");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* @todo Document check. 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("live error UniqueID \"Label\"");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("message \"message\" {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("live error anotherid \"Label\"");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("message \"message {0}, {1}\" {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("def Name");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("for Category list {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("issue anotherid on list bind (3, 2) data (\"\")");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("val size =");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("if (list.checks !== null) list.checks.size else 0");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("if (list.checks?.size > 1) {");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("// SL: string value of list");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("String::valueOf(list)");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("issue UniqueID on list#checks[0]");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("/* ML: string value of size       */");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("String::valueOf(size)");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("@SeverityRange(warning .. error)");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("onSave error lastID \"Label\"");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("message \"message\" {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("// single line comment");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("/**");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("* This check is javadoc-like commented.");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("warning CategoryNamedW \"Category named W\" (boolean foo = false, boolean bar = true)");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("message \"Category named \'w\'\" {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("for Category c {");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("if (\'w\'.equalsIgnoreCase(c.name)) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("issue");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    final String input = _builder.toString();

    _formatterTestHelper.assertFormatted((FormatterTestRequest it) -> {
      // these preferences are usually picked up from the resource, but we are not using a resource here.
      MapBasedPreferenceValues prefs = new MapBasedPreferenceValues();
      prefs.put(FormatterPreferenceKeys.indentation, "  ");
      it.getRequest().setPreferences(prefs);
      it.setToBeFormatted(input);
      it.setExpectation(input);
    });
  }

  /**
   * Test that spaces and new lines are added where expected.
   */
  @Test
  public void testWSAdded() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package com.avaloq.tools.ddk.check.formatting import com.avaloq.tools.ddk.check.check.* catalog CheckFormattingTest");
    _builder.newLine();
    _builder.append("for grammar com.avaloq.tools.ddk.check.Check{category \"Label\"{/**");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* @todo Document check. 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("*/live error UniqueID \"Label\"");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("message \"message\"{}live error anotherid \"Label\"");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("message \"message {0}, {1}\" {}}");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("def Name for Category list{issue anotherid on list bind(3,2)data(\"\")");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("val size=if(list.checks !== null)list.checks.size else 0");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("if(list.checks?.size>1){");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("// SL: string value of list");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("String::valueOf(list)issue UniqueID on list#checks[0]}else{/* ML: string value of size       */String::valueOf(size)}}");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("@SeverityRange(warning..error)onSave error lastID\"Label\"message \"message\" {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("// single line comment");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}/**");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("* This check is javadoc-like commented.");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("*/warning CategoryNamedW \"Category named W\"(boolean foo=false,boolean bar=true)message \"Category named \'w\'\"{");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("for Category c {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("if(\'w\'.equalsIgnoreCase(c.name)){issue}");
    _builder.newLine();
    _builder.append("}}}");
    _builder.newLine();
    final String input = _builder.toString();

    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("package com.avaloq.tools.ddk.check.formatting");
    _builder_1.newLine();
    _builder_1.append("import com.avaloq.tools.ddk.check.check.*");
    _builder_1.newLine();
    _builder_1.append("catalog CheckFormattingTest");
    _builder_1.newLine();
    _builder_1.append("for grammar com.avaloq.tools.ddk.check.Check {");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("category \"Label\" {");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("/**");
    _builder_1.newLine();
    _builder_1.append("   ");
    _builder_1.append("* @todo Document check. 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890");
    _builder_1.newLine();
    _builder_1.append("   ");
    _builder_1.append("*/");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("live error UniqueID \"Label\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("message \"message\" {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("live error anotherid \"Label\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("message \"message {0}, {1}\" {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("def Name");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("for Category list {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("issue anotherid on list bind (3, 2) data (\"\")");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("val size =");
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("if (list.checks !== null) list.checks.size else 0");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("if (list.checks?.size > 1) {");
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("// SL: string value of list");
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("String::valueOf(list)");
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("issue UniqueID on list#checks[0]");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("} else { /* ML: string value of size       */");
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("String::valueOf(size)");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("@SeverityRange(warning .. error)");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("onSave error lastID \"Label\"");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("message \"message\" {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("// single line comment");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("/**");
    _builder_1.newLine();
    _builder_1.append("   ");
    _builder_1.append("* This check is javadoc-like commented.");
    _builder_1.newLine();
    _builder_1.append("   ");
    _builder_1.append("*/");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("warning CategoryNamedW \"Category named W\" (boolean foo = false, boolean bar = true)");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("message \"Category named \'w\'\" {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("for Category c {");
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("if (\'w\'.equalsIgnoreCase(c.name)) {");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("issue");
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    final String expected = _builder_1.toString();

    _formatterTestHelper.assertFormatted((FormatterTestRequest it) -> {
      // these preferences are usually picked up from the resource, but we are not using a resource here.
      MapBasedPreferenceValues prefs = new MapBasedPreferenceValues();
      prefs.put(FormatterPreferenceKeys.indentation, "  ");
      it.getRequest().setPreferences(prefs);
      it.setToBeFormatted(input);
      it.setExpectation(expected);
    });
  }

  /**
   * Test that additional spaces and new lines are removed
   */
  @Test
  public void testWSRemoved() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("    ");
    _builder.append("package");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("com.avaloq.tools.ddk.check.formatting");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("import");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("com.avaloq.tools.ddk.check.check.*");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("catalog");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("CheckFormattingTest");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("for");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("grammar");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("com.avaloq.tools.ddk.check.Check");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("{");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("category");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("\"Label\"");
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("{");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("/**");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* @todo Document check. 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("*/");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("live");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("error");
    _builder.newLine();
    _builder.newLine();
    _builder.append("     ");
    _builder.append("UniqueID");
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("\"Label\"");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("message");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("     ");
    _builder.append("\"message\"");
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("{");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("live      error      anotherid     \"Label\"");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("message      \"message {0}, {1}\"           {");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("def");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("Name");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("for");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("Category");
    _builder.newLine();
    _builder.newLine();
    _builder.append("   ");
    _builder.append("list");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("issue");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("     ");
    _builder.append("anotherid");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("on");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("list");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("bind");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("         ");
    _builder.append("(");
    _builder.newLine();
    _builder.newLine();
    _builder.append("         ");
    _builder.append("3");
    _builder.newLine();
    _builder.newLine();
    _builder.append("         ");
    _builder.append(",");
    _builder.newLine();
    _builder.newLine();
    _builder.append("          ");
    _builder.append("2");
    _builder.newLine();
    _builder.newLine();
    _builder.append("          ");
    _builder.append(")");
    _builder.newLine();
    _builder.newLine();
    _builder.append("           ");
    _builder.append("data");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("(");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("\"\"");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append(")");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("val");
    _builder.newLine();
    _builder.newLine();
    _builder.append("     ");
    _builder.append("size");
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("=");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("if");
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("(");
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("list");
    _builder.newLine();
    _builder.append("      ");
    _builder.append(".");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("checks");
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("!==");
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("null");
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append(")");
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("list   .   checks   .   size");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("else");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("0");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("if");
    _builder.newLine();
    _builder.newLine();
    _builder.append("     ");
    _builder.append("(");
    _builder.newLine();
    _builder.newLine();
    _builder.append("     ");
    _builder.append("list.checks   ?.   size");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("> 1)");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("{");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("// SL: string value of list");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("String");
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("::");
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("valueOf");
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("(");
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("list");
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append(")");
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("issue UniqueID on list   #    checks");
    _builder.newLine();
    _builder.newLine();
    _builder.append("         ");
    _builder.append("[");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("0");
    _builder.newLine();
    _builder.newLine();
    _builder.append("       ");
    _builder.append("]");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("     ");
    _builder.append("else");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("     ");
    _builder.append("{");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("/* ML: string value of size       */");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("String     ::    valueOf   (   size  )");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("@");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("SeverityRange");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("(");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("warning");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("..");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("error");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append(")");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("onSave error lastID \"Label\"");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("message \"message\" {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// single line comment");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("/**");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("* This check is javadoc-like commented.");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("*/");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("warning    CategoryNamedW    \"Category named W\"");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("(");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("boolean");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("foo");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("=");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("false");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append(",");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("boolean");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("bar");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("=");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("true");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append(")");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("message \"Category named \'w\'\" {");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("for Category c {");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("if (\'w\'.equalsIgnoreCase(c.name)) {");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("issue");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("      ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    final String input = _builder.toString();

    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("package com.avaloq.tools.ddk.check.formatting");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import com.avaloq.tools.ddk.check.check.*");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("catalog CheckFormattingTest");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("for grammar com.avaloq.tools.ddk.check.Check {");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("category \"Label\" {");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("/**");
    _builder_1.newLine();
    _builder_1.append("     ");
    _builder_1.append("* @todo Document check. 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 1234567890");
    _builder_1.newLine();
    _builder_1.append("     ");
    _builder_1.append("*/");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("live error UniqueID \"Label\"");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("message \"message\" {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("live error anotherid \"Label\"");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("message \"message {0}, {1}\" {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("def Name");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("for Category list {");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("issue anotherid on list bind (3, 2) data (\"\")");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("val size =");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("if (list.checks !== null) list.checks.size else 0");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("if (list.checks?.size > 1) {");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("// SL: string value of list");
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("String::valueOf(");
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("list");
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append(")");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("issue UniqueID on list#checks[0]");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("} else {");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("/* ML: string value of size       */");
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("String::valueOf(size)");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("@SeverityRange(warning .. error)");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("onSave error lastID \"Label\"");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("message \"message\" {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("// single line comment");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("/**");
    _builder_1.newLine();
    _builder_1.append("   ");
    _builder_1.append("* This check is javadoc-like commented.");
    _builder_1.newLine();
    _builder_1.append("   ");
    _builder_1.append("*/");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("warning CategoryNamedW \"Category named W\" (boolean foo = false,");
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("boolean bar = true)");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("message \"Category named \'w\'\" {");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("for Category c {");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("if (\'w\'.equalsIgnoreCase(c.name)) {");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("        ");
    _builder_1.append("issue");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("      ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("  ");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    final String expected = _builder_1.toString();

    _formatterTestHelper.assertFormatted((FormatterTestRequest it) -> {
      // these preferences are usually picked up from the resource, but we are not using a resource here.
      MapBasedPreferenceValues prefs = new MapBasedPreferenceValues();
      prefs.put(FormatterPreferenceKeys.indentation, "  ");
      it.getRequest().setPreferences(prefs);
      it.setToBeFormatted(input);
      it.setExpectation(expected);
    });
  }
}
