/*
 * generated by Xtext 2.14.0
 */
package com.avaloq.tools.ddk.xtext.format.ui;

import com.avaloq.tools.ddk.xtext.format.ui.builder.FormatBuilderParticipant;
import com.avaloq.tools.ddk.xtext.format.ui.hyperlinking.FormatHyperlinkHelper;
import com.avaloq.tools.ddk.xtext.ui.templates.KeywordAwareCrossReferenceTemplateVariableResolver;
import com.google.inject.Binder;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.builder.IXtextBuilderParticipant;
import org.eclipse.xtext.ui.editor.hyperlinking.IHyperlinkHelper;
import org.eclipse.xtext.ui.editor.templates.CrossReferenceTemplateVariableResolver;
import org.eclipse.xtext.xtext.generator.model.project.IXtextProjectConfig;
import org.eclipse.xtext.xtext.generator.model.project.XtextProjectConfig;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FormatUiModule extends AbstractFormatUiModule {

  public FormatUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }

  /**
   * Binds a {@link CrossReferenceTemplateVariableResolver} which prefixes keywords with escape characters.
   *
   * @return {@link KeywordAwareCrossReferenceTemplateVariableResolver}
   */
  public Class<? extends CrossReferenceTemplateVariableResolver> bindCrossReferenceTemplateVariableResolver() {
    return KeywordAwareCrossReferenceTemplateVariableResolver.class;
  }

  /**
   * Bind hyperlink helper to provide hyperlinking from "override" keyword to extended rule.
   *
   * @return FormatHyperlinkHelper.class
   */
  @Override
  public Class<? extends IHyperlinkHelper> bindIHyperlinkHelper() {
    return FormatHyperlinkHelper.class;
  }

  @Override
  public Class<? extends IXtextBuilderParticipant> bindIXtextBuilderParticipant() {
    return FormatBuilderParticipant.class;
  }

  @Override
  public void configure(final Binder binder) {
    super.configure(binder);
    binder.bind(IXtextProjectConfig.class).to(XtextProjectConfig.class);
  }
}
