/*
 * generated by Xtext 2.25.0
 */
package com.avaloq.tools.ddk.xtext.expression.ide;

/**
 * Use this class to register ide components.
 */
public class ExpressionIdeModule extends AbstractExpressionIdeModule {
}
