/*******************************************************************************
 * Copyright (c) 2016 Avaloq Group AG and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Avaloq Group AG - initial API and implementation
 *******************************************************************************/

package com.avaloq.tools.ddk.xtext.generator.builder;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.eclipse.osgi.util.NLS;
import org.eclipse.xtend2.lib.StringConcatenationClient;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.GeneratedMetamodel;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.xbase.lib.StringExtensions;
import org.eclipse.xtext.xtext.generator.AbstractXtextGeneratorFragment;
import org.eclipse.xtext.xtext.generator.XtextGeneratorNaming;
import org.eclipse.xtext.xtext.generator.model.FileAccessFactory;
import org.eclipse.xtext.xtext.generator.model.TypeReference;

import com.google.inject.Inject;


@SuppressWarnings("nls")
public class LspBuilderIntegrationFragment2 extends AbstractXtextGeneratorFragment {

  private static final Logger LOGGER = LogManager.getLogger(LspBuilderIntegrationFragment2.class);

  @Inject
  private FileAccessFactory fileAccessFactory;

  @Inject
  private XtextGeneratorNaming packageNaming;

  private TypeReference createSuffixedTypeReference(final String suffix) {
    return new TypeReference(packageNaming.getGenericIdeBasePackage(getGrammar()), GrammarUtil.getSimpleName(getGrammar()) + suffix);
  }

  protected TypeReference getLspBuildSetupGeneratedClass() {
    return createSuffixedTypeReference("LspBuildSetupGenerated");
  }

  protected TypeReference getLspBuildSetupServiceClass() {
    return createSuffixedTypeReference("LspBuildSetupService");
  }

  @Override
  public void generate() {
    if (getProjectConfig().getGenericIde().isEnabled()) {
      if (LOGGER.isInfoEnabled()) {
        LOGGER.info(NLS.bind("executing generate for {0}", getClass().getName()));
      }
      generateServiceRegistration();
      generateBuildService();
      generateBuildSetup();
    }
  }

  public void generateServiceRegistration() {
    StringConcatenationClient client = new StringConcatenationClient() {
      @Override
      protected void appendTo(final TargetStringConcatenation builder) {
        builder.append(getLspBuildSetupServiceClass().getName());
        builder.newLineIfNotEmpty();
      }
    };
    fileAccessFactory.createTextFile("META-INF/services/com.avaloq.tools.ddk.xtext.build.ILspLanguageSetup", client).writeTo(getProjectConfig().getGenericIde().getSrcGen());
  }

  // CHECKSTYLE:CONSTANTS-OFF
  public void generateBuildService() {
    final TypeReference lspBuildSetupServiceClass = getLspBuildSetupServiceClass();
    StringConcatenationClient client = new StringConcatenationClient() {
      @Override
      protected void appendTo(final TargetStringConcatenation builder) {
        builder.append("""
        import java.util.List;

        import com.avaloq.tools.ddk.xtext.build.AbstractDynamicSetupService;
        import com.avaloq.tools.ddk.xtext.build.ILspLanguageSetup;
        import com.google.common.collect.ImmutableList;
        import com.google.inject.Injector;
        import com.google.inject.Module;

        /**
         * Generated by com.avaloq.tools.ddk.xtext.generator.builder.LspBuilderIntegrationFragment2.
         */
        public class %s extends AbstractDynamicSetupService implements ILspLanguageSetup {
        """.formatted(getLspBuildSetupServiceClass().getSimpleName()));
        builder.newLine();
        builder.append("  ");
        builder.append("@SuppressWarnings(\"nls\")");
        builder.newLine();
        builder.append("  ");
        builder.append("private static final String GRAMMAR = \"");
        builder.append(getGrammar().getName(), "  ");
        builder.append("\";");
        builder.newLineIfNotEmpty();
        builder.append("  ");
        builder.append("@SuppressWarnings(\"nls\")");
        builder.newLine();
        builder.append("  ");
        builder.append("private static final List<String> PARENTS = ImmutableList.of(//");
        builder.newLine();
        builder.append("     ");
        boolean hasElements = false;
        for (final Grammar g : GrammarUtil.allUsedGrammars(getGrammar())) {
          if (!hasElements) {
            hasElements = true;
          } else {
            builder.appendImmediate("\n,", "     ");
          }
          builder.append("\"");
          builder.append(g.getName(), "     ");
          builder.append("\" //");
        }
        builder.newLineIfNotEmpty();
        builder.append("  ");
        builder.append(");");
        builder.newLine();
        builder.newLine();
        builder.append("  ");
        builder.append("public Injector doSetup(Module overrideModule, Module... additionalModules) {");
        builder.newLine();
        builder.append("    ");
        builder.append("return new ");
        builder.append(GrammarUtil.getSimpleName(getGrammar()), "    ");
        builder.append("LspBuildSetupGenerated(SETUP_LOCK, overrideModule, additionalModules).createInjectorAndDoEMFRegistration();");
        builder.newLineIfNotEmpty();
        builder.append("""
          }

          @Override
          public List<String> getParentLanguages() {
            return PARENTS;
          }

          @Override
          public String getLanguageName() {
            return GRAMMAR;
          }

        }
        """);
      }
    };
    fileAccessFactory.createJavaFile(lspBuildSetupServiceClass, client).writeTo(getProjectConfig().getGenericIde().getSrcGen());
  }

  public void generateBuildSetup() {
    final TypeReference lspBuildSetupGeneratedClass = getLspBuildSetupGeneratedClass();
    StringConcatenationClient client = new StringConcatenationClient() {
      @Override
      protected void appendTo(final TargetStringConcatenation builder) {
        builder.append("""
        import org.eclipse.xtext.util.Modules2;

        import com.google.common.collect.ImmutableList;
        import com.google.inject.Guice;
        import com.google.inject.Injector;
        import com.google.inject.Module;
        import com.google.inject.util.Modules;


        /**
         * Generated by com.avaloq.tools.ddk.xtext.generator.builder.LspBuilderIntegrationFragment2.
         */
        """);
        builder.append("public class ");
        builder.append(getLspBuildSetupGeneratedClass().getSimpleName());
        builder.append(" extends ");
        builder.append(packageNaming.getGenericIdeSetup(getGrammar()));
        builder.append(" {");
        builder.newLineIfNotEmpty();
        builder.newLine();
        builder.append("  ");
        builder.append("private final Module overrideModule;");
        builder.newLine();
        builder.append("  ");
        builder.append("private final Module[] additionalModules;");
        builder.newLine();
        builder.append("  ");
        builder.append("private final Object lock;");
        builder.newLine();
        builder.newLine();
        builder.append("  ");
        builder.append("public ");
        builder.append(getLspBuildSetupGeneratedClass().getSimpleName(), "  ");
        builder.append("(final Object lock, final Module overrideModule, Module... additionalModules) {");
        builder.newLineIfNotEmpty();
        builder.append("    ");
        builder.append("this.lock = lock;");
        builder.newLine();
        builder.append("    ");
        builder.append("this.overrideModule = overrideModule;");
        builder.newLine();
        builder.append("    ");
        builder.append("this.additionalModules = additionalModules;");
        builder.newLine();
        builder.append("  ");
        builder.append("}");
        builder.newLine();
        builder.newLine();
        builder.append("  ");
        builder.append("public ");
        builder.append(getLspBuildSetupGeneratedClass().getSimpleName(), "  ");
        builder.append("(final Module overrideModule, Module... additionalModules) {");
        builder.newLineIfNotEmpty();
        builder.append("    ");
        builder.append("this.lock = null;");
        builder.newLine();
        builder.append("    ");
        builder.append("this.overrideModule = overrideModule;");
        builder.newLine();
        builder.append("    ");
        builder.append("this.additionalModules = additionalModules;");
        builder.newLine();
        builder.append("  ");
        builder.append("}");
        builder.newLine();
        builder.newLine();
        builder.append("""
          @Override
          public Injector createInjectorAndDoEMFRegistration() {
            registerEPackages();
            Injector injector = createInjector();
            if (lock != null) {
              synchronized (lock)  {
                register(injector);
              }
            } else {
              register(injector);
            }
            return injector;
          }

          @Override
          public Injector createInjector() {
            return Guice.createInjector(getModules());
          }

        """);
        builder.append("  ");
        builder.append("protected void registerEPackages() {");
        builder.newLine();
        for (final GeneratedMetamodel mmd : EcoreUtil2.<GeneratedMetamodel>typeSelect(getGrammar().getMetamodelDeclarations(), GeneratedMetamodel.class)) {
          builder.append("    ");
          builder.append("if (");
          builder.append(GrammarUtil.getNamespace(getGrammar()), "    ");
          builder.append(".");
          builder.append(mmd.getName(), "    ");
          builder.append(".");
          builder.append(StringExtensions.toFirstUpper(mmd.getName()), "    ");
          builder.append("Package.eINSTANCE == null) {");
          builder.newLineIfNotEmpty();
          builder.append("    ");
          builder.append("  ");
          builder.append("throw new IllegalStateException(\"EPackage could not be initialized: \" + ");
          builder.append(GrammarUtil.getNamespace(getGrammar()), "      ");
          builder.append(".");
          builder.append(mmd.getName(), "      ");
          builder.append(".");
          builder.append(StringExtensions.toFirstUpper(mmd.getName()), "      ");
          builder.append("Package.eNS_URI); //$NON-NLS-1$");
          builder.newLineIfNotEmpty();
          builder.append("    ");
          builder.append("}");
          builder.newLine();
        }
        builder.append("  ");
        builder.append("}");
        builder.newLine();
        builder.newLine();
        builder.append("  ");
        builder.append("protected Iterable<Module> getModules() {");
        builder.newLine();
        builder.append("    ");
        builder.append("return ImmutableList.<Module> builder().add(Modules.override(Modules2.mixin(new ");
        builder.append(getGrammar().getName(), "    ");
        builder.append("RuntimeModule(), new ");
        builder.append(packageNaming.getGenericIdeModule(getGrammar()), "    ");
        builder.append("())).with(overrideModule)).add(additionalModules).build();");
        builder.newLineIfNotEmpty();
        builder.append("  ");
        builder.append("}");
        builder.newLine();
        builder.newLine();
        builder.append("}");
        builder.newLine();
      }
    };
    fileAccessFactory.createJavaFile(lspBuildSetupGeneratedClass, client).writeTo(getProjectConfig().getGenericIde().getSrcGen());
  }

}
