/*******************************************************************************
 * Copyright (c) 2016 Avaloq Group AG and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Avaloq Group AG - initial API and implementation
 *******************************************************************************/

package com.avaloq.tools.ddk.xtext.generator.builder;

import java.util.List;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.eclipse.osgi.util.NLS;
import org.eclipse.xtend2.lib.StringConcatenationClient;
import org.eclipse.xtext.AbstractMetamodelDeclaration;
import org.eclipse.xtext.GeneratedMetamodel;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.xbase.lib.StringExtensions;
import org.eclipse.xtext.xtext.generator.AbstractXtextGeneratorFragment;
import org.eclipse.xtext.xtext.generator.model.FileAccessFactory;
import org.eclipse.xtext.xtext.generator.model.TypeReference;

import com.google.inject.Inject;


@SuppressWarnings("nls")
public class StandaloneBuilderIntegrationFragment2 extends AbstractXtextGeneratorFragment {

  private static final Logger LOGGER = LogManager.getLogger(StandaloneBuilderIntegrationFragment2.class);

  @Inject
  private FileAccessFactory fileAccessFactory;

  private TypeReference createSuffixedTypeReference(final String suffix) {
    return new TypeReference(
      getGrammar().getName() + suffix
    );
  }

  protected TypeReference getStandaloneBuildSetupGeneratedClass() {
    return createSuffixedTypeReference("StandaloneBuildSetupGenerated");
  }

  protected TypeReference getStandaloneBuildSetupServiceClass() {
    return createSuffixedTypeReference("StandaloneBuildSetupService");
  }

  @Override
  public void generate() {
    if (LOGGER.isInfoEnabled()) {
      LOGGER.info(NLS.bind("executing generate for {0}", getClass().getName()));
    }
    generateServiceRegistration();
    generateBuildService();
    generateBuildSetup();
  }

  public void generateServiceRegistration() {
    String content = getStandaloneBuildSetupServiceClass().getName() + '\n';
    fileAccessFactory.createTextFile("META-INF/services/com.avaloq.tools.ddk.xtext.build.IDynamicSetupService",
      toClient(content)).writeTo(getProjectConfig().getRuntime().getSrcGen());
  }

  // CHECKSTYLE:CONSTANTS-OFF
  public void generateBuildService() {
    final Grammar grammar = getGrammar();
    final TypeReference standaloneBuildSetupServiceClass = getStandaloneBuildSetupServiceClass();
    StringBuilder sb = new StringBuilder(2048);
    sb.append("""
    import java.util.List;

    import com.avaloq.tools.ddk.xtext.build.AbstractDynamicSetupService;
    import com.google.common.collect.ImmutableList;
    import com.google.inject.Injector;
    import com.google.inject.Module;

    /**
     * Generated by com.avaloq.tools.ddk.xtext.generator.builder.StandaloneBuilderIntegrationFragment2.
     */
    public class %s extends AbstractDynamicSetupService {

      @SuppressWarnings("nls")
      private static final String GRAMMAR = "%s";
      @SuppressWarnings("nls")
      private static final List<String> PARENTS = ImmutableList.of(//
    """.formatted(standaloneBuildSetupServiceClass.getSimpleName(), grammar.getName()));
    List<Grammar> allUsedGrammars = GrammarUtil.allUsedGrammars(grammar);
    boolean hasElements = false;
    for (Grammar g : allUsedGrammars) {
      if (!hasElements) {
        hasElements = true;
        sb.append("     ");
      } else {
        sb.append("\n     ,");
      }
      sb.append('"').append(g.getName()).append("\" //");
    }
    if (hasElements) {
      sb.append('\n');
    }
    sb.append("""
      );

      public Injector doSetup(Module overrideModule, Module... additionalModules) {
        return new %sStandaloneBuildSetupGenerated(SETUP_LOCK, overrideModule, additionalModules).createInjectorAndDoEMFRegistration();
      }

      @Override
      public List<String> getParentLanguages() {
        return PARENTS;
      }

      @Override
      public String getLanguageName() {
        return GRAMMAR;
      }

    }
    """.formatted(GrammarUtil.getSimpleName(grammar)));
    fileAccessFactory.createJavaFile(standaloneBuildSetupServiceClass,
      toClient(sb)).writeTo(getProjectConfig().getRuntime().getSrcGen());
  }

  public void generateBuildSetup() {
    final Grammar grammar = getGrammar();
    final TypeReference standaloneBuildSetupGeneratedClass = getStandaloneBuildSetupGeneratedClass();
    StringBuilder sb = new StringBuilder(2048);
    sb.append("""
    import com.google.common.collect.ImmutableList;
    import com.google.inject.Guice;
    import com.google.inject.Injector;
    import com.google.inject.Module;
    import com.google.inject.util.Modules;


    /**
     * Generated by com.avaloq.tools.ddk.xtext.generator.builder.StandaloneBuilderIntegrationFragment2.
     */
    public class %s extends %sStandaloneSetup {

      private final Module overrideModule;
      private final Module[] additionalModules;
      private final Object lock;

      public %s(final Object lock, final Module overrideModule, Module... additionalModules) {
        this.lock = lock;
        this.overrideModule = overrideModule;
        this.additionalModules = additionalModules;
      }

      public %s(final Module overrideModule, Module... additionalModules) {
        this.lock = null;
        this.overrideModule = overrideModule;
        this.additionalModules = additionalModules;
      }

      @Override
      public Injector createInjectorAndDoEMFRegistration() {
        registerEPackages();
        Injector injector = createInjector();
        if (lock != null) {
          synchronized (lock)  {
            register(injector);
          }
        } else {
          register(injector);
        }
        return injector;
      }

      @Override
      public Injector createInjector() {
        return Guice.createInjector(getModules());
      }

    """.formatted(standaloneBuildSetupGeneratedClass.getSimpleName(), GrammarUtil.getSimpleName(grammar),
        standaloneBuildSetupGeneratedClass.getSimpleName(), standaloneBuildSetupGeneratedClass.getSimpleName()));
    sb.append("  protected void registerEPackages() {\n");
    for (AbstractMetamodelDeclaration decl : grammar.getMetamodelDeclarations()) {
      if (decl instanceof GeneratedMetamodel) {
        GeneratedMetamodel mmd = (GeneratedMetamodel) decl;
        String ns = GrammarUtil.getNamespace(grammar);
        String name = mmd.getName();
        String nameUpper = StringExtensions.toFirstUpper(name);
        sb.append("    if (").append(ns).append('.').append(name).append('.').append(nameUpper).append("Package.eINSTANCE == null) {\n");
        sb.append("      throw new IllegalStateException(\"EPackage could not be initialized: \" + ").append(ns).append('.').append(name).append('.').append(nameUpper).append("Package.eNS_URI); //$NON-NLS-1$\n");
        sb.append("    }\n");
      }
    }
    sb.append("  }\n");
    sb.append('\n');
    sb.append("""
      protected Iterable<Module> getModules() {
        return ImmutableList.<Module> builder().add(Modules.override(new %sRuntimeModule()).with(overrideModule)).add(additionalModules).build();
      }

    }
    """.formatted(grammar.getName()));
    fileAccessFactory.createJavaFile(standaloneBuildSetupGeneratedClass,
      toClient(sb)).writeTo(getProjectConfig().getRuntime().getSrcGen());
  }
  // CHECKSTYLE:CONSTANTS-ON

  private static StringConcatenationClient toClient(final CharSequence sb) {
    final String content = sb.toString();
    return new StringConcatenationClient() {
      @Override
      protected void appendTo(final TargetStringConcatenation target) {
        target.append(content);
      }
    };
  }

}
