/*
 * generated by Xtext
 */
package com.avaloq.tools.ddk.xtext.export.generator;

import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGenerator2;
import org.eclipse.xtext.generator.IGeneratorContext;

import com.avaloq.tools.ddk.xtext.export.export.ExportModel;
import com.avaloq.tools.ddk.xtext.expression.generator.CompilationContext;
import com.avaloq.tools.ddk.xtext.expression.generator.GenModelUtilX;
import com.avaloq.tools.ddk.xtext.expression.generator.Naming;
import com.google.inject.Inject;


/**
 * Generates code from your model files on save.
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
public class ExportGenerator implements IGenerator2 {

  @Inject
  private ExportGeneratorSupport generatorSupport;
  @Inject
  private Naming naming;
  @Inject
  private ExportGeneratorX exportGeneratorX;

  @Inject
  private GenModelUtilX genModelUtil;

  @Inject
  private ExportedNamesProviderGenerator exportedNamesProviderGenerator;
  @Inject
  private ResourceDescriptionManagerGenerator resourceDescriptionManagerGenerator;
  @Inject
  private ResourceDescriptionStrategyGenerator resourceDescriptionStrategyGenerator;
  @Inject
  private ResourceDescriptionConstantsGenerator resourceDescriptionConstantsGenerator;
  @Inject
  private FingerprintComputerGenerator fingerprintComputerGenerator;
  @Inject
  private FragmentProviderGenerator fragmentProviderGenerator;
  @Inject
  private ExportFeatureExtensionGenerator exportFeatureExtensionGenerator;

  private CompilationContext compilationContext;

  @Override
  public void doGenerate(final Resource input, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    if (input == null || input.getContents().isEmpty() || !(input.getContents().get(0) instanceof ExportModel)) {
      return;
    }
    final ExportModel model = (ExportModel) input.getContents().get(0);
    genModelUtil.setResource(model.eResource());
    IProject project = null;
    if (input.getURI().isPlatformResource()) {
      final org.eclipse.core.resources.IResource res = ResourcesPlugin.getWorkspace().getRoot().findMember(input.getURI().toPlatformString(true));
      if (res != null) {
        project = res.getProject();
      }
    }

    generatorSupport.executeWithProjectResourceLoader(project, () -> {
      compilationContext = generatorSupport.getCompilationContext(model, genModelUtil);

      generateExportedNamesProvider(model, fsa);
      generateResourceDescriptionManager(model, fsa);
      generateResourceDescriptionStrategy(model, fsa);
      generateResourceDescriptionConstants(model, fsa);
      generateFingerprintComputer(model, fsa);
      generateFragmentProvider(model, fsa);
      generateFeatureExtension(model, fsa);
    });
  }

  public void generateExportedNamesProvider(final ExportModel model, final IFileSystemAccess fsa) {
    final String fileName = naming.toFileName(exportGeneratorX.getExportedNamesProvider(model));
    fsa.generateFile(fileName, exportedNamesProviderGenerator.generate(model, compilationContext, genModelUtil));
  }

  public void generateResourceDescriptionManager(final ExportModel model, final IFileSystemAccess fsa) {
    if (!model.isExtension()) {
      final String fileName = naming.toFileName(exportGeneratorX.getResourceDescriptionManager(model));
      fsa.generateFile(fileName, ExportOutputConfigurationProvider.STUB_OUTPUT, resourceDescriptionManagerGenerator.generate(model, compilationContext, genModelUtil));
    }
  }

  public void generateResourceDescriptionStrategy(final ExportModel model, final IFileSystemAccess fsa) {
    final String fileName = naming.toFileName(exportGeneratorX.getResourceDescriptionStrategy(model));
    fsa.generateFile(fileName, resourceDescriptionStrategyGenerator.generate(model, compilationContext, genModelUtil));
  }

  public void generateResourceDescriptionConstants(final ExportModel model, final IFileSystemAccess fsa) {
    final String fileName = naming.toFileName(exportGeneratorX.getResourceDescriptionConstants(model));
    fsa.generateFile(fileName, resourceDescriptionConstantsGenerator.generate(model, compilationContext, genModelUtil));
  }

  public void generateFingerprintComputer(final ExportModel model, final IFileSystemAccess fsa) {
    final String fileName = naming.toFileName(exportGeneratorX.getFingerprintComputer(model));
    fsa.generateFile(fileName, fingerprintComputerGenerator.generate(model, compilationContext, genModelUtil));
  }

  public void generateFragmentProvider(final ExportModel model, final IFileSystemAccess fsa) {
    final String fileName = naming.toFileName(exportGeneratorX.getFragmentProvider(model));
    if (model.getExports().stream().anyMatch(e -> e.isFingerprint() && e.getFragmentAttribute() != null) || model.isExtension()) {
      fsa.generateFile(fileName, fragmentProviderGenerator.generate(model, compilationContext, genModelUtil));
    } else if (!model.getExports().isEmpty()) {
      final StringBuilder sb = new StringBuilder();
      sb.append("package ").append(naming.toJavaPackage(exportGeneratorX.getFragmentProvider(model))).append(";\n");
      sb.append("\n");
      sb.append("import com.avaloq.tools.ddk.xtext.linking.ShortFragmentProvider;\n");
      sb.append("\n");
      sb.append("\n");
      sb.append("public class ").append(naming.toSimpleName(exportGeneratorX.getFragmentProvider(model))).append(" extends ShortFragmentProvider {\n");
      sb.append("\n");
      sb.append("}\n");
      fsa.generateFile(fileName, sb);
    }
  }

  public void generateFeatureExtension(final ExportModel model, final IFileSystemAccess fsa) {
    if (model.isExtension()) {
      final String fileName = naming.toFileName(exportGeneratorX.getExportFeatureExtension(model));
      fsa.generateFile(fileName, exportFeatureExtensionGenerator.generate(model, compilationContext, genModelUtil));
    }
  }

  @Override
  public void afterGenerate(final Resource input, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
  }

  @Override
  public void beforeGenerate(final Resource input, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
  }
}
