/*
 * generated by Xtext
 */
package com.avaloq.tools.ddk.xtext.export.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.avaloq.tools.ddk.xtext.export.services.ExportGrammarAccess;

public class ExportParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ExportGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.avaloq.tools.ddk.xtext.export.parser.antlr.internal.InternalExportParser createParser(XtextTokenStream stream) {
		return new com.avaloq.tools.ddk.xtext.export.parser.antlr.internal.InternalExportParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ExportModel";
	}
	
	public ExportGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ExportGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
