/*
 * generated by Xtext 2.27.0.M1
 */
package com.avaloq.tools.ddk.sample.helloworld.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class HelloWorldAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/avaloq/tools/ddk/sample/helloworld/parser/antlr/internal/InternalHelloWorld.tokens");
	}
}
