/*
 * generated by Xtext
 */
package com.avaloq.tools.ddk.xtext.export.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractExportJavaValidator extends com.avaloq.tools.ddk.xtext.expression.validation.ExpressionJavaValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.avaloq.tools.ddk.xtext.export.export.ExportPackage.eINSTANCE);
		return result;
	}

}
