/*
 * generated by Xtext 2.27.0.M3
 */
package com.avaloq.tools.ddk.xtext.format.scoping;

import org.eclipse.xtext.xbase.annotations.typesystem.XbaseWithAnnotationsBatchScopeProvider;

public abstract class AbstractFormatScopeProvider extends XbaseWithAnnotationsBatchScopeProvider {
}
