/*
 * generated by Xtext
 */
package com.avaloq.tools.ddk.xtext.export.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.avaloq.tools.ddk.xtext.export.ui.internal.ExportActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ExportExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ExportActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ExportActivator.getInstance().getInjector(ExportActivator.COM_AVALOQ_TOOLS_DDK_XTEXT_EXPORT_EXPORT);
	}
	
}
